server:
  port: 4444

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useSSL=false
    username: bitai
    password: 456123
    driver-class-name: com.mysql.cj.jdbc.Driver